[2024-11-11T21:31:01.539+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-11T21:31:01.674+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_run manual__2024-11-11T21:31:00.296026+00:00 [queued]>
[2024-11-11T21:31:01.689+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_run manual__2024-11-11T21:31:00.296026+00:00 [queued]>
[2024-11-11T21:31:01.689+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-11T21:31:01.734+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2024-11-11 21:31:00.296026+00:00
[2024-11-11T21:31:01.742+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'BuildELT_dbt', 'dbt_run', 'manual__2024-11-11T21:31:00.296026+00:00', '--job-id', '206', '--raw', '--subdir', 'DAGS_FOLDER/build_elt_with_dbt.py', '--cfg-path', '/tmp/tmpxe9bf_zr']
[2024-11-11T21:31:01.745+0000] {standard_task_runner.py:91} INFO - Job 206: Subtask dbt_run
[2024-11-11T21:31:01.747+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=403) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-11T21:31:01.748+0000] {standard_task_runner.py:63} INFO - Started process 404 to run task
[2024-11-11T21:31:01.800+0000] {task_command.py:426} INFO - Running <TaskInstance: BuildELT_dbt.dbt_run manual__2024-11-11T21:31:00.296026+00:00 [running]> on host 2992e781c734
[2024-11-11T21:31:01.973+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BuildELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-11-11T21:31:00.296026+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-11T21:31:00.296026+00:00'
[2024-11-11T21:31:01.974+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-11T21:31:02.001+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-11T21:31:02.002+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt']
[2024-11-11T21:31:02.004+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-11T21:31:02.005+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 234, in execute
    result = self.subprocess_hook.run_command(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/subprocess.py", line 77, in run_command
    self.sub_process = Popen(
                       ^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.12/subprocess.py", line 1872, in _execute_child
    env_list.append(k + b'=' + os.fsencode(v))
                               ^^^^^^^^^^^^^^
  File "<frozen os>", line 818, in fsencode
TypeError: expected str, bytes or os.PathLike object, not NoneType
[2024-11-11T21:31:02.016+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=BuildELT_dbt, task_id=dbt_run, run_id=manual__2024-11-11T21:31:00.296026+00:00, execution_date=20241111T213100, start_date=20241111T213101, end_date=20241111T213102
[2024-11-11T21:31:02.030+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 206 for task dbt_run (expected str, bytes or os.PathLike object, not NoneType; 404)
[2024-11-11T21:31:02.044+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-11T21:31:02.078+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-11T21:31:02.082+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
